/**
 * THIS FILE IS AUTO-GENERATED BY NOTION-CMS
 * DO NOT EDIT DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN
 *
 * Generated for database: NoCMS
 */
import {
  DatabaseRecord,
  NotionCMS,
  QueryBuilder,
  DatabaseFieldMetadata,
} from "@mikemajara/notion-cms";
export const RecordNoCMSFieldTypes = {
  id: { type: "unique_id" },
  _slug: { type: "formula" },
  Tags: {
    type: "multi_select",
    options: ["Onboarding", "Design"] as const,
  },
  "Sub-page": { type: "relation" },
  "Last edited time": { type: "last_edited_time" },
  "Parent page": { type: "relation" },
  Name: { type: "title" },
  Verification: { type: "verification" },
  Owner: { type: "people" },
  slug: { type: "rich_text" },
  Order: { type: "number" },
} as const satisfies DatabaseFieldMetadata;

export interface RecordNoCMSAdvanced {
  id: string;
  _slug: { type: string; value: any };
  Tags: { id: string; name: string; color: string }[];
  "Sub-page": { id: string }[];
  "Last edited time": { timestamp: string; date: Date };
  "Parent page": { id: string }[];
  Name: {
    content: string;
    annotations: any;
    href: string | null;
    link?: { url: string } | null;
  }[];
  Verification: any;
  Owner: {
    id: string;
    name: string | null;
    avatar_url: string | null;
    object: string;
    type: string;
    email?: string;
  }[];
  slug: {
    content: string;
    annotations: any;
    href: string | null;
    link?: { url: string } | null;
  }[];
  Order: number;
}

export interface RecordNoCMSRaw {
  id: string;
  properties: Record<string, any>;
}

export interface RecordNoCMS extends DatabaseRecord {
  id: string;
  _slug: any;
  Tags: Array<"Onboarding" | "Design">;
  "Sub-page": string[];
  "Last edited time": string;
  "Parent page": string[];
  Name: string;
  Verification: any;
  Owner: string[];
  slug: string;
  Order: number;
  advanced: RecordNoCMSAdvanced;
  raw: RecordNoCMSRaw;
}

// Extend NotionCMS class with database-specific method
/* eslint-disable */
declare module "@mikemajara/notion-cms" {
  interface NotionCMS {
    /**
     * Type-safe query method for the NoCMS database
     * @param databaseId The ID of the database to query
     * @returns A type-safe QueryBuilder for the RecordNoCMS record type
     */
    queryNoCMS(
      databaseId: string
    ): QueryBuilder<RecordNoCMS, typeof RecordNoCMSFieldTypes>;
  }
}

// Implement the method on the NotionCMS prototype
NotionCMS.prototype.queryNoCMS = function (
  databaseId: string
): QueryBuilder<RecordNoCMS, typeof RecordNoCMSFieldTypes> {
  return this.query<RecordNoCMS, typeof RecordNoCMSFieldTypes>(
    databaseId,
    RecordNoCMSFieldTypes
  );
};
