/**
 * THIS FILE IS AUTO-GENERATED BY NOTION-CMS
 * DO NOT EDIT DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN
 * v0.1.3
 * Generated for database: blog
 * Composite display: blog (Data source: blog)
 * Signature name: blog
 * Data source: 22f2a789-c1fc-81d1-b32b-000b116f92f5
 */
import { DatabaseRecord, NotionCMS, DatabaseFieldMetadata } from "@notion-utils/cms";
import { PageObjectResponse } from "@notionhq/client/build/src/api-endpoints";

export { NotionCMS } from "@notion-utils/cms";
export const RecordBlogFieldTypes = {
  "id": { type: "unique_id" },
  "likes": { type: "number" },
  "_title": { type: "rich_text" },
  "Keywords": { 
    type: "multi_select",
    options: ["Manage Gmail inbox", "Gmail shortcuts", "Gmail labels", "Gmail productivity tips", "Gmail inbox organization", "Euphemism"] as const
  },
  "tags": { 
    type: "multi_select",
    options: ["content-creation", "lifestyle", "tech", "social", "blog", "nextjs", "notion", "tutorial", "filosofia", "speech", "family", "wedding", "tool", "react", "fivetran", "pipeline", "data", "postgresql", "trigger", "problem-solving", "psicologia", "life", "chakra-ui", "npm", "opinion", "sql-server", "finance", "projects", "auth", "authentication", "supabase", "alfred", "clipboard", "history", "hacks", "vercel", "automation", "lambda-function", "api", "integration", "google-sheets", "noSQL", "SQL", "work", "chat-gpt", "twitter", "ai", "openai", "google", "productivity", "gtd", "indiehacker", "snowflake", "design", "dev", "business", "cli", "scripting", "guide", "press", "periódicos", "articulea", "news", "forms", "chrome", "tabs", "shadcnui", "Computer Science"] as const
  },
  "createdAt": { type: "created_time" },
  "slug": { type: "rich_text" },
  "series": { 
    type: "select",
    options: ["Productivity", "None"] as const
  },
  "publishedAt": { type: "date" },
  "isPublished": { type: "checkbox" },
  "meta-title": { type: "rich_text" },
  "author": { type: "rich_text" },
  "editedAt": { type: "last_edited_time" },
  "Automatic fields": { type: "rich_text" },
  "archive": { type: "checkbox" },
  "locale": { 
    type: "select",
    options: ["en", "es"] as const
  },
  "meta-summary": { type: "rich_text" },
  "isProtected": { type: "checkbox" },
  "Related": { type: "relation" },
  "summary": { type: "rich_text" },
  "name": { type: "title" },
} as const satisfies DatabaseFieldMetadata;

export interface RecordBlogAdvanced {
    id: string;
    likes: number;
    _title: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    Keywords: { id: string; name: string; color: string }[];
    tags: { id: string; name: string; color: string }[];
    createdAt: { timestamp: string; date: Date };
    slug: { type: string; value: any };
    series: { id: string; name: string; color: string } | null;
    publishedAt: { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    isPublished: boolean;
    "meta-title": { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    author: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    editedAt: { timestamp: string; date: Date };
    "Automatic fields": { type: string; value: any };
    archive: boolean;
    locale: { id: string; name: string; color: string } | null;
    "meta-summary": { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    isProtected: boolean;
    Related: { id: string }[];
    summary: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    name: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
}

export interface RecordBlogRaw {
    id: string;
    properties: Record<string, any>;
}

export interface RecordBlog extends DatabaseRecord {
    id: string;
    likes: number;
    _title: string;
    Keywords: Array<"Manage Gmail inbox" | "Gmail shortcuts" | "Gmail labels" | "Gmail productivity tips" | "Gmail inbox organization" | "Euphemism">;
    tags: Array<"content-creation" | "lifestyle" | "tech" | "social" | "blog" | "nextjs" | "notion" | "tutorial" | "filosofia" | "speech" | "family" | "wedding" | "tool" | "react" | "fivetran" | "pipeline" | "data" | "postgresql" | "trigger" | "problem-solving" | "psicologia" | "life" | "chakra-ui" | "npm" | "opinion" | "sql-server" | "finance" | "projects" | "auth" | "authentication" | "supabase" | "alfred" | "clipboard" | "history" | "hacks" | "vercel" | "automation" | "lambda-function" | "api" | "integration" | "google-sheets" | "noSQL" | "SQL" | "work" | "chat-gpt" | "twitter" | "ai" | "openai" | "google" | "productivity" | "gtd" | "indiehacker" | "snowflake" | "design" | "dev" | "business" | "cli" | "scripting" | "guide" | "press" | "periódicos" | "articulea" | "news" | "forms" | "chrome" | "tabs" | "shadcnui" | "Computer Science">;
    createdAt: string;
    slug: any;
    series: "Productivity" | "None";
    publishedAt: Date;
    isPublished: boolean;
    "meta-title": string;
    author: string;
    editedAt: string;
    "Automatic fields": any;
    archive: boolean;
    locale: "en" | "es";
    "meta-summary": string;
    isProtected: boolean;
    Related: string[];
    summary: string;
    name: string;
}

// Extend DatabaseRegistry interface with this database
declare module "@notion-utils/cms" {
  interface DatabaseRegistry {
    blog: {
      record: RecordBlog;
      recordAdvanced: RecordBlogAdvanced;
      recordRaw: PageObjectResponse;
      fields: typeof RecordBlogFieldTypes;
    };
  }
}

// Add database configuration to the registry
NotionCMS.prototype.databases["blog"] = {
  dataSourceId: process.env.NOTION_CMS_BLOG_DATA_SOURCE_ID || "22f2a789-c1fc-81d1-b32b-000b116f92f5",
  label: "blog (Data source: blog)",
  fields: RecordBlogFieldTypes,
};

