/**
 * THIS FILE IS AUTO-GENERATED BY NOTION-CMS
 * DO NOT EDIT DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN
 *
 * Generated for database: Product Catalog
 */
import {
  DatabaseRecord,
  NotionCMS,
  QueryBuilder,
  DatabaseFieldMetadata
} from "@mikemajara/notion-cms"
export const RecordProductCatalogFieldTypes = {
  id: { type: "unique_id" },
  SKU: { type: "rich_text" },
  Category: {
    type: "select",
    options: [
      "Electronics",
      "Clothing",
      "Home & Kitchen",
      "Accessories",
      "Sports & Fitness",
      "Home & Garden",
      "Home & Office",
      "Health & Nutrition",
      "Home & Wellness",
      "Office Supplies"
    ] as const
  },
  "In Stock": { type: "checkbox" },
  Image: { type: "files" },
  Tags: {
    type: "multi_select",
    options: [
      "Audio",
      "Wireless",
      "Noise-Canceling",
      "Organic",
      "Cotton",
      "Casual",
      "Smart",
      "Coffee",
      "WiFi",
      "Leather",
      "Laptop",
      "Handcrafted",
      "Portable",
      "Charger",
      "Fast-Charging",
      "Yoga",
      "Eco-Friendly",
      "Non-Slip",
      "Stainless Steel",
      "Insulated",
      "Ergonomic",
      "Precision",
      "Ceramic",
      "Handmade",
      "Plants",
      "Running",
      "Lightweight",
      "Cushioning",
      "Blue Light",
      "Computer",
      "Eye Protection",
      "Bamboo",
      "Sustainable",
      "Kitchen",
      "LED",
      "Adjustable",
      "Touch Controls",
      "Protein",
      "Whey",
      "Vanilla",
      "Canvas",
      "Tote",
      "Shopping",
      "Essential Oils",
      "Aromatherapy",
      "Color-Changing",
      "Shockproof",
      "Silicone",
      "Protection",
      "Notebook",
      "Lined",
      "Hardcover",
      "Earbuds",
      "Noise Cancellation",
      "Digital",
      "Precise"
    ] as const
  },
  Description: { type: "rich_text" },
  ID: { type: "unique_id" },
  Price: { type: "number" },
  Name: { type: "title" }
} as const satisfies DatabaseFieldMetadata

export interface RecordProductCatalogAdvanced {
  id: string
  SKU: {
    content: string
    annotations: any
    href: string | null
    link?: { url: string } | null
  }[]
  Category: { id: string; name: string; color: string } | null
  "In Stock": boolean
  Image: {
    name: string
    type: string
    external?: { url: string }
    file?: { url: string; expiry_time: string }
  }[]
  Tags: { id: string; name: string; color: string }[]
  Description: {
    content: string
    annotations: any
    href: string | null
    link?: { url: string } | null
  }[]
  ID: { prefix: string | null; number: number }
  Price: number
  Name: {
    content: string
    annotations: any
    href: string | null
    link?: { url: string } | null
  }[]
}

export interface RecordProductCatalogRaw {
  id: string
  properties: Record<string, any>
}

export interface RecordProductCatalog extends DatabaseRecord {
  id: string
  SKU: string
  Category:
    | "Electronics"
    | "Clothing"
    | "Home & Kitchen"
    | "Accessories"
    | "Sports & Fitness"
    | "Home & Garden"
    | "Home & Office"
    | "Health & Nutrition"
    | "Home & Wellness"
    | "Office Supplies"
  "In Stock": boolean
  Image: { name: string; url: string }[]
  Tags: Array<
    | "Audio"
    | "Wireless"
    | "Noise-Canceling"
    | "Organic"
    | "Cotton"
    | "Casual"
    | "Smart"
    | "Coffee"
    | "WiFi"
    | "Leather"
    | "Laptop"
    | "Handcrafted"
    | "Portable"
    | "Charger"
    | "Fast-Charging"
    | "Yoga"
    | "Eco-Friendly"
    | "Non-Slip"
    | "Stainless Steel"
    | "Insulated"
    | "Ergonomic"
    | "Precision"
    | "Ceramic"
    | "Handmade"
    | "Plants"
    | "Running"
    | "Lightweight"
    | "Cushioning"
    | "Blue Light"
    | "Computer"
    | "Eye Protection"
    | "Bamboo"
    | "Sustainable"
    | "Kitchen"
    | "LED"
    | "Adjustable"
    | "Touch Controls"
    | "Protein"
    | "Whey"
    | "Vanilla"
    | "Canvas"
    | "Tote"
    | "Shopping"
    | "Essential Oils"
    | "Aromatherapy"
    | "Color-Changing"
    | "Shockproof"
    | "Silicone"
    | "Protection"
    | "Notebook"
    | "Lined"
    | "Hardcover"
    | "Earbuds"
    | "Noise Cancellation"
    | "Digital"
    | "Precise"
  >
  Description: string
  ID: any
  Price: number
  Name: string
  advanced: RecordProductCatalogAdvanced
  raw: RecordProductCatalogRaw
}

// Extend DatabaseRegistry interface with this database
declare module "@mikemajara/notion-cms" {
  interface DatabaseRegistry {
    productCatalog: {
      record: RecordProductCatalog
      fields: typeof RecordProductCatalogFieldTypes
    }
  }
}

// Add database configuration to the registry
if (!NotionCMS.prototype.databases) {
  NotionCMS.prototype.databases = {}
}
NotionCMS.prototype.databases.productCatalog = {
  id:
    process.env.NOTION_CMS_PRODUCTCATALOG_DATABASE_ID ||
    "2362a789c1fc8170b076ee5cd46cdd87",
  fields: RecordProductCatalogFieldTypes
}
