/**
 * THIS FILE IS AUTO-GENERATED BY NOTION-CMS
 * DO NOT EDIT DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN
 * 
 * Generated for database: Resource Tracker
 */
import { DatabaseRecord, NotionPropertyType } from "./notion-types";
import { PropertyItemObjectResponse } from "@notionhq/client/build/src/api-endpoints";

// Use PropertyItemObjectResponse for property type definitions
type NotionProperty<T extends NotionPropertyType> = PropertyItemObjectResponse;

export interface AdvancedResourceTrackerRecord {
    id: string;
    "Last Review Date": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    "Estimated Monthly Cost": number;
    "Tag Compliance": boolean;
    Owner: { id: string; name: string | null; avatar_url: string | null; object: string; type: string; email?: string }[];
    "Last Used Date": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    "Service Name": { id: string; name: string; color: string }[];
    "Linked Project / Jira Ticket": string;
    "Can Be Deprovisioned": boolean;
    Environment: { id: string; name: string; color: string } | null;
    "Auto Shutdown Configured": boolean;
    "Instance Size / Tier": { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    "Estimated Monthly Cost (USD)": number;
    "Provision Date": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    "Resource Type": { id: string; name: string; color: string } | null;
    Region: { id: string; name: string; color: string } | null;
    Team: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    Notes: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    "Is Active": boolean;
    "Reviewed by DevOps": { id: string; name: string; color: string } | null;
    "Reason for Keeping": { id: string; name: string; color: string }[];
    ID: { prefix: string | null; number: number };
    Title: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
}

export interface RawResourceTrackerRecord {
    id: string;
    properties: Record<string, any>;
}

export interface ResourceTrackerRecord extends DatabaseRecord {
    "Last Review Date": Date;
    "Estimated Monthly Cost": number;
    "Tag Compliance": boolean;
    Owner: { id: string; name: string | null; avatar_url: string | null; }[];
    "Last Used Date": Date;
    "Service Name": string[];
    "Linked Project / Jira Ticket": string;
    "Can Be Deprovisioned": boolean;
    Environment: string;
    "Auto Shutdown Configured": boolean;
    "Instance Size / Tier": string;
    "Estimated Monthly Cost (USD)": number;
    "Provision Date": Date;
    "Resource Type": string;
    Region: string;
    Team: string;
    Notes: string;
    "Is Active": boolean;
    "Reviewed by DevOps": any;
    "Reason for Keeping": string[];
    ID: any;
    Title: string;
    advanced: AdvancedResourceTrackerRecord;
    raw: RawResourceTrackerRecord;
}

export interface ResourceTrackerRecordProperties {
    "Last Review Date": NotionProperty<'date'>;
    "Estimated Monthly Cost": NotionProperty<'number'>;
    "Tag Compliance": NotionProperty<'checkbox'>;
    Owner: NotionProperty<'people'>;
    "Last Used Date": NotionProperty<'date'>;
    "Service Name": NotionProperty<'multi_select'>;
    "Linked Project / Jira Ticket": NotionProperty<'url'>;
    "Can Be Deprovisioned": NotionProperty<'checkbox'>;
    Environment: NotionProperty<'select'>;
    "Auto Shutdown Configured": NotionProperty<'checkbox'>;
    "Instance Size / Tier": NotionProperty<'rich_text'>;
    "Estimated Monthly Cost (USD)": NotionProperty<'number'>;
    "Provision Date": NotionProperty<'date'>;
    "Resource Type": NotionProperty<'select'>;
    Region: NotionProperty<'select'>;
    Team: NotionProperty<'rich_text'>;
    Notes: NotionProperty<'rich_text'>;
    "Is Active": NotionProperty<'checkbox'>;
    "Reviewed by DevOps": NotionProperty<'status'>;
    "Reason for Keeping": NotionProperty<'multi_select'>;
    ID: NotionProperty<'unique_id'>;
    Title: NotionProperty<'title'>;
}
