/**
 * THIS FILE IS AUTO-GENERATED BY NOTION-CMS
 * DO NOT EDIT DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN
 */
import { PropertyItemObjectResponse, PageObjectResponse } from "@notionhq/client/build/src/api-endpoints";
import { DatabaseRecord, NotionPropertyType, getPropertyValue, simplifyNotionRecord, simplifyNotionRecords, createSimplifyFunction, createSimplifyRecordsFunction } from "notion-cms";

// Re-export types and functions from the library
export type { DatabaseRecord, NotionPropertyType };
export { 
  getPropertyValue,
  simplifyNotionRecord,
  simplifyNotionRecords,
  createSimplifyFunction,
  createSimplifyRecordsFunction
};

export interface DatabaseProperties {
}
