/**
 * THIS FILE IS AUTO-GENERATED BY NOTION-CMS
 * DO NOT EDIT DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN
 * 
 * Generated for database: Art Gallery Inventory
 */
import { DatabaseRecord, NotionCMS, QueryBuilder, DatabaseFieldMetadata } from "@mikemajara/notion-cms";
export const RecordArtGalleryInventoryFieldTypes = {
  "id": { type: "unique_id" },
  "Artist": { type: "rich_text" },
  "Date Acquired": { type: "date" },
  "Date Sold": { type: "date" },
  "Image": { type: "files" },
  "Published": { type: "checkbox" },
  "Price": { type: "number" },
  "Medium": { 
    type: "select",
    options: ["Oil Paint", "Acrylic", "Watercolor", "Sculpture", "Mixed Media", "Digital", "Charcoal/Graphite", "Photography", "Textile", "Glass", "Painting", "Charcoal", "Installation"] as const
  },
  "Commission Rate": { type: "number" },
  "Dimensions": { type: "rich_text" },
  "Status": { type: "status" },
  "Description": { type: "rich_text" },
  "Artwork Title": { type: "title" },
} as const satisfies DatabaseFieldMetadata;

export interface RecordArtGalleryInventoryAdvanced {
    id: string;
    Artist: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    "Date Acquired": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    "Date Sold": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    Image: { name: string; type: string; external?: { url: string }; file?: { url: string; expiry_time: string } }[];
    Published: boolean;
    Price: number;
    Medium: { id: string; name: string; color: string } | null;
    "Commission Rate": number;
    Dimensions: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    Status: { id: string; name: string; color: string } | null;
    Description: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    "Artwork Title": { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
}

export interface RecordArtGalleryInventoryRaw {
    id: string;
    properties: Record<string, any>;
}

export interface RecordArtGalleryInventory extends DatabaseRecord {
    id: string;
    Artist: string;
    "Date Acquired": Date;
    "Date Sold": Date;
    Image: { name: string; url: string; }[];
    Published: boolean;
    Price: number;
    Medium: "Oil Paint" | "Acrylic" | "Watercolor" | "Sculpture" | "Mixed Media" | "Digital" | "Charcoal/Graphite" | "Photography" | "Textile" | "Glass" | "Painting" | "Charcoal" | "Installation";
    "Commission Rate": number;
    Dimensions: string;
    Status: any;
    Description: string;
    "Artwork Title": string;
    advanced: RecordArtGalleryInventoryAdvanced;
    raw: RecordArtGalleryInventoryRaw;
}

// Extend NotionCMS class with database-specific method
/* eslint-disable */
declare module "@mikemajara/notion-cms" {
  interface NotionCMS {
    /**
     * Type-safe query method for the Art Gallery Inventory database
     * @param databaseId The ID of the database to query
     * @returns A type-safe QueryBuilder for the RecordArtGalleryInventory record type
     */
    queryArtGalleryInventory(databaseId: string): QueryBuilder<RecordArtGalleryInventory, typeof RecordArtGalleryInventoryFieldTypes>;
  }
}

// Implement the method on the NotionCMS prototype
NotionCMS.prototype.queryArtGalleryInventory = function(databaseId: string): QueryBuilder<RecordArtGalleryInventory, typeof RecordArtGalleryInventoryFieldTypes> {
  return this.query<RecordArtGalleryInventory, typeof RecordArtGalleryInventoryFieldTypes>(databaseId, RecordArtGalleryInventoryFieldTypes);
};

