/**
 * THIS FILE IS AUTO-GENERATED BY NOTION-CMS
 * DO NOT EDIT DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN
 * v0.1.3
 * Generated for database: ERP
 * Composite name: ERP (Data source: Projects)
 * Data source: 2822a789-c1fc-805e-8128-000b5966657b
 */
import { DatabaseRecord, NotionCMS, DatabaseFieldMetadata } from "@mikemajara/notion-cms";
import { PageObjectResponse } from "@notionhq/client/build/src/api-endpoints";

export { NotionCMS } from "@mikemajara/notion-cms";
export const RecordERPProjectsFieldTypes = {
  "id": { type: "unique_id" },
  "Project Lead": { type: "people" },
  "Team Members": { type: "people" },
  "Client": { type: "relation" },
  "Type": { 
    type: "select",
    options: ["Internal", "Enterprise", "Small Business", "Startup", "Government", "Non-Profit", "Educational"] as const
  },
  "Priority": { 
    type: "select",
    options: ["Low", "Medium", "High", "Critical"] as const
  },
  "Price": { type: "number" },
  "Start Date": { type: "date" },
  "Due Date": { type: "date" },
  "Status": { type: "status" },
  "Project Name": { type: "title" },
} as const satisfies DatabaseFieldMetadata;

export interface RecordERPProjectsAdvanced {
    id: string;
    "Project Lead": { id: string; name: string | null; avatar_url: string | null; object: string; type: string; email?: string }[];
    "Team Members": { id: string; name: string | null; avatar_url: string | null; object: string; type: string; email?: string }[];
    Client: { id: string }[];
    Type: { id: string; name: string; color: string } | null;
    Priority: { id: string; name: string; color: string } | null;
    Price: number;
    "Start Date": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    "Due Date": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    Status: { id: string; name: string; color: string } | null;
    "Project Name": { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
}

export interface RecordERPProjectsRaw {
    id: string;
    properties: Record<string, any>;
}

export interface RecordERPProjects extends DatabaseRecord {
    id: string;
    "Project Lead": string[];
    "Team Members": string[];
    Client: string[];
    Type: "Internal" | "Enterprise" | "Small Business" | "Startup" | "Government" | "Non-Profit" | "Educational";
    Priority: "Low" | "Medium" | "High" | "Critical";
    Price: number;
    "Start Date": Date;
    "Due Date": Date;
    Status: any;
    "Project Name": string;
}

// Extend DatabaseRegistry interface with this database
declare module "@mikemajara/notion-cms" {
  interface DatabaseRegistry {
    eRPDataSourceProjects: {
      record: RecordERPProjects;
      recordAdvanced: RecordERPProjectsAdvanced;
      recordRaw: PageObjectResponse;
      fields: typeof RecordERPProjectsFieldTypes;
    };
  }
}

// Add database configuration to the registry
NotionCMS.prototype.databases["eRPDataSourceProjects"] = {
  dataSourceId: process.env.NOTION_CMS_ERPDATASOURCEPROJECTS_DATA_SOURCE_ID || "2822a789-c1fc-805e-8128-000b5966657b",
  label: "ERP (Data source: Projects)",
  fields: RecordERPProjectsFieldTypes,
};

