/**
 * THIS FILE IS AUTO-GENERATED BY NOTION-CMS
 * DO NOT EDIT DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN
 * v0.1.3
 * Generated for database: ERP
 * Composite name: ERP (Data source: Clients)
 * Data source: 2822a789-c1fc-800f-8c84-000b8af56baf
 */
import { DatabaseRecord, NotionCMS, DatabaseFieldMetadata } from "@mikemajara/notion-cms";
import { PageObjectResponse } from "@notionhq/client/build/src/api-endpoints";

export { NotionCMS } from "@mikemajara/notion-cms";
export const RecordERPClientsFieldTypes = {
  "id": { type: "unique_id" },
  "Contact Person": { type: "rich_text" },
  "Tags": { 
    type: "multi_select",
    options: ["VIP", "Lead", "Active", "Inactive", "Corporate", "Individual", "Prospect", "Churned"] as const
  },
  "Last Contact": { type: "date" },
  "Next Follow-up": { type: "date" },
  "Deal Value": { type: "number" },
  "Phone": { type: "phone_number" },
  "Projects": { type: "relation" },
  "Status": { type: "status" },
  "Email": { type: "email" },
  "Client Name": { type: "title" },
} as const satisfies DatabaseFieldMetadata;

export interface RecordERPClientsAdvanced {
    id: string;
    "Contact Person": { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
    Tags: { id: string; name: string; color: string }[];
    "Last Contact": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    "Next Follow-up": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    "Deal Value": number;
    Phone: string;
    Projects: { id: string }[];
    Status: { id: string; name: string; color: string } | null;
    Email: string;
    "Client Name": { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
}

export interface RecordERPClientsRaw {
    id: string;
    properties: Record<string, any>;
}

export interface RecordERPClients extends DatabaseRecord {
    id: string;
    "Contact Person": string;
    Tags: Array<"VIP" | "Lead" | "Active" | "Inactive" | "Corporate" | "Individual" | "Prospect" | "Churned">;
    "Last Contact": Date;
    "Next Follow-up": Date;
    "Deal Value": number;
    Phone: string;
    Projects: string[];
    Status: any;
    Email: string;
    "Client Name": string;
}

// Extend DatabaseRegistry interface with this database
declare module "@mikemajara/notion-cms" {
  interface DatabaseRegistry {
    eRPDataSourceClients: {
      record: RecordERPClients;
      recordAdvanced: RecordERPClientsAdvanced;
      recordRaw: PageObjectResponse;
      fields: typeof RecordERPClientsFieldTypes;
    };
  }
}

// Add database configuration to the registry
NotionCMS.prototype.databases["eRPDataSourceClients"] = {
  dataSourceId: process.env.NOTION_CMS_ERPDATASOURCECLIENTS_DATA_SOURCE_ID || "2822a789-c1fc-800f-8c84-000b8af56baf",
  label: "ERP (Data source: Clients)",
  fields: RecordERPClientsFieldTypes,
};

