/**
 * THIS FILE IS AUTO-GENERATED BY NOTION-CMS
 * DO NOT EDIT DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN
 * v0.1.3
 * Generated for database: Just antoher database
 * Composite name: Just antoher database (Data source: Just antoher database)
 * Data source: 2772a789-c1fc-806c-9977-000bc90190c5
 */
import { DatabaseRecord, NotionCMS, DatabaseFieldMetadata } from "@mikemajara/notion-cms";
import { PageObjectResponse } from "@notionhq/client/build/src/api-endpoints";

export { NotionCMS } from "@mikemajara/notion-cms";
export const RecordJustAntoherDatabaseJustAntoherDatabaseFieldTypes = {
  "id": { type: "unique_id" },
  "Status": { type: "status" },
  "Creation Date": { type: "date" },
  "Assigned To": { type: "people" },
  "Name": { type: "title" },
} as const satisfies DatabaseFieldMetadata;

export interface RecordJustAntoherDatabaseJustAntoherDatabaseAdvanced {
    id: string;
    Status: { id: string; name: string; color: string } | null;
    "Creation Date": { start: string; end: string | null; time_zone: string | null; parsedStart: Date | null; parsedEnd: Date | null } | null;
    "Assigned To": { id: string; name: string | null; avatar_url: string | null; object: string; type: string; email?: string }[];
    Name: { content: string; annotations: any; href: string | null; link?: { url: string } | null }[];
}

export interface RecordJustAntoherDatabaseJustAntoherDatabaseRaw {
    id: string;
    properties: Record<string, any>;
}

export interface RecordJustAntoherDatabaseJustAntoherDatabase extends DatabaseRecord {
    id: string;
    Status: any;
    "Creation Date": Date;
    "Assigned To": string[];
    Name: string;
}

// Extend DatabaseRegistry interface with this database
declare module "@mikemajara/notion-cms" {
  interface DatabaseRegistry {
    justAntoherDatabaseDataSourceJustAntoherDatabase: {
      record: RecordJustAntoherDatabaseJustAntoherDatabase;
      recordAdvanced: RecordJustAntoherDatabaseJustAntoherDatabaseAdvanced;
      recordRaw: PageObjectResponse;
      fields: typeof RecordJustAntoherDatabaseJustAntoherDatabaseFieldTypes;
    };
  }
}

// Add database configuration to the registry
NotionCMS.prototype.databases["justAntoherDatabaseDataSourceJustAntoherDatabase"] = {
  dataSourceId: process.env.NOTION_CMS_JUSTANTOHERDATABASEDATASOURCEJUSTANTOHERDATABASE_DATA_SOURCE_ID || "2772a789-c1fc-806c-9977-000bc90190c5",
  label: "Just antoher database (Data source: Just antoher database)",
  fields: RecordJustAntoherDatabaseJustAntoherDatabaseFieldTypes,
};

